---
- hosts: localhost
  vars_files:
    - ./vars/vars.yml
  tasks:

    - name: get ec2 instance id by its name tag
      ec2_instance_facts:
        filters:
          availability-zone: eu-central-1a
      register: ec2_metadata

    - debug: msg="{{ ec2_metadata.instances }}"