---
- hosts: localhost
  vars_files:
    - ./vars/vault.yml
    - ./vars/vars.yml
  tasks:

    - name: Get AWS Details
      ec2_group:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        filters:
          availability-zone: eu-central-1
      register: ec2_name

    - name: Get instance IP addresses.
      debug:
        msg: "{{ item.0 }} | {{ item.1 }} | {{ item.2 }}"
      with_together:
        - "{{ ec2_name.instances | map(attribute='tags.Name') | list }}"