---
- hosts: localhost
  vars_files:
    - ./vars/vault.yml
    - ./vars/vars.yml
  tasks:

  # Block is a Group of Tasks combined together
  - name: Get Info Block
    block: 
      - name: Get Running instance Info
        
        ec2_instance_info:
        register: ec2info 

      - name: Print info
        debug: var="ec2info.instances"

    # - name: Create Security Group for Ansible
    #   ec2_group:
    #       name: Ansible_Security_Group
    #       description: Allow Traffic on port 22 and 80
    #       region: eu-central-1
    #       rules:
    #        - proto: tcp
    #          from_port: 80
    #          to_port: 80
    #          cidr_ip: 0.0.0.0/0

    #        - proto: tcp
    #          from_port: 22
    #          to_port: 22
    #          cidr_ip: 0.0.0.0/0

    #        - proto: icmp
    #          from_port: -1
    #          to_port: -1
    #          cidr_ip: 0.0.0.0/0
    #       rules_egress:
    #        - proto: all
    #          cidr_ip: 0.0.0.0/0
    #       vpc_id: "{{ aws_vpc_id }}"

    # - name: Provision EC2 instance
    #   ec2:
    #      key_name: "{{ aws_sec_key }}"
    #      region: eu-central-1
    #      instance_type: "{{ aws_instance_type }}"
    #      image: "{{ aws_ami_id }}"
    #      wait: yes
    #      wait_timeout: 500
    #      count: 1
    #      instance_tags:
    #         Name: AWS-Ansible
    #      volumes:
    #         - device_name: /dev/xvda
    #           volume_type: gp2
    #           volume_size: 8
    #      monitoring: yes
    #      vpc_subnet_id: "{{ aws_sub_id }}"
    #      assign_public_ip: yes
    #      group: Ansible_Security_Group
    #   register: ec2

    # - name: Wait for SSH to come up
    #   wait_for:
    #     debug: var=item.public_dns_name
    #   with_items: "{{ ec2.instances }}"

